---
- name: Ensure smartmontools is installed
  package: name=smartmontools state=present
  when: physical_device_install_smartmontools

- name: Ensure the timeout on the DHCP client is not the default 5 minutes
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    regexp: '^timeout '
    line: "timeout {{ physical_device_dhclient_timeout }};"

- name: Ensure the timezone is set appropriately
  timezone: name="{{ physical_device_timezone }}"
  when: physical_device_timezone
  notify: restart cron

- name: Ensure the locale exists
  locale_gen:
    name: "{{ physical_device_locale }}"
    state: present
  when: physical_device_locale

- name: Ensure the default locale is set
  command: "update-locale LANG={{ physical_device_locale }}"
  when: physical_device_locale
